In [1]:
import torch

In [4]:
# 张量表示一个数值组成的数组,这个数组可能有多个纬度
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
# 我们可以通过张量的shape属性来访问张量的形状和张量中元素的总数
x.shape

torch.Size([12])

In [8]:
# 元素总数
x.numel()

12

In [9]:
# 要改变一个张量的形状而不改变元素数量和元素值,我们可以调用 reshape 函数
x = x.reshape(3, 4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [31]:
# 使用全0,全1,其他常量或者从特定分布中随机采样的数字
"""
在PyTorch中，张量的形状是从最外层到最内层排列的。
比如，形状(2,3,4)意味着第一个维度有2个元素，每个元素是一个3x4的矩阵；
第二个维度有3个元素，每个是长度为4的向量；
第三个维度是每个向量中的4个元素。
"""
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [13]:
# 通过提供包含数值的python列表(或嵌套列表)来为所需张量中的每个元素赋以确定值
torch.tensor(
    [[2, 1, 4, 3],
    [1, 2, 3, 4],
    [4, 3, 2, 1]]
).shape

torch.Size([3, 4])

In [17]:
# 常见的标准算术运算符(+, -, *, / 和 **)都可以被升级为按元素运算
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x ** y  # **运算符是求幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([ 1.,  4., 16., 64.]))

In [18]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [22]:
# 合并张量
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
# 分别在第0维和第1维合并,即按行和按列合并
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [23]:
# 通过逻辑运算符构建二维张量
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [24]:
# 对张量中的所有元素进行求和会产生一个只有一个元素的张量
X.sum()

tensor(66.)

In [26]:
# 即使形状不同,我们仍然可以通过调用广播机制(broadcasting mechanism)来执行按元素操作
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [28]:
"""
在广播机制下，a 和 b分别扩展为：
[[0, 0],
 [1, 1],
 [2, 2]]

[[0, 1],
 [0, 1],
 [0, 1]] 
"""
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [29]:
""" 元素访问
可以用[-1]选择最后一个元素,
可以用[1:3]选择第二个和第三个元素
"""
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [30]:
# 除读取外,我们还可以通过指定索引来将元素写入矩阵
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [32]:
# 为多个元素赋相同的值,只需要索引所有元素,然后为它们赋值
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [33]:
# 运行一些操作可能会导致为新结果分配内存
before = id(Y)
Y = Y + X
id(Y) == before

False

In [35]:
Z = torch.zeros_like(Y)  # 继承Y的type和shape,但元素均为1
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 2446309287000
id(Z): 2446309287000


In [36]:
# 如果在后续计算中没有重复使用X,我们也可以使用 X[:] = X + Y or X += Y 来减少操作的内存开销
before = id(X)
X += Y
id(X) == before

True

In [37]:
# 转换为 Numpy 张量
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [38]:
# 将大小为1的张量转换为 python 标量
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)