In [10]:
# 构造一个没有任何参数的自定义层
import torch 
import torch.nn.functional as F
from torch import nn

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [11]:
# 将层作为组件合并到构建更复杂的模型中
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

Y = net(torch.rand(4, 8))
Y.mean()

tensor(5.5879e-09, grad_fn=<MeanBackward0>)

In [40]:
# 带参数的图层
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

dense = MyLinear(5, 3)
dense.weight

Parameter containing:
tensor([[ 0.2794,  2.2758,  1.1733],
        [ 0.7213,  0.3368, -0.9643],
        [-0.3804,  0.7570,  1.5997],
        [-0.1466, -0.0640,  0.0615],
        [-0.8043,  1.3541,  0.3374]], requires_grad=True)

In [41]:
# 使用自定义层直接执行正向传播计算
dense(torch.rand(2, 5))

tensor([[0.0000, 0.5483, 0.0000],
        [0.0000, 1.0373, 0.0000]])

In [42]:
# 使用自定义层构建模型
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[0.9992],
        [1.2335]])